[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/tours/*"
  to = "/.netlify/functions/scraper:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/scraper"
  status = 200

[functions]
  node_bundler = "esbuild"